[repositories]
rugpi-extra = { git = "https://github.com/silitics/rugpi-extra.git", branch = "v0.7" }

# Image based on Raspberry Pi OS using the `tryboot` feature for A/B booting.
#
# This image supports the Raspberry Pi 4 and 5 family of devices.
#
# Note that Raspberry Pi 4 devices need to have the latest firmware installed.
[images.rpi-raspios]
layer = "rpi-raspios"
architecture = "arm64"
target = "rpi-tryboot"

# Like the `rpi-raspios-tryboot` image but with the firmware update for Raspberry Pi 4.
[images.rpi-raspios-pi4]
layer = "rpi-raspios-pi4"
architecture = "arm64"
target = "rpi-tryboot"

# Image based on Debian using the `tryboot` feature for A/B booting.
#
# This image supports the Raspberry Pi 4 and 5 family of devices.
#
# Note that Raspberry Pi 4 devices need to have the latest firmware installed.
[images.rpi-debian]
layer = "rpi-debian"
architecture = "arm64"
target = "rpi-tryboot"

# Image based on Debian for EFI AMD64 systems.
[images.efi-debian-amd64]
layer = "efi-debian"
architecture = "amd64"
target = "generic-grub-efi"

# Image based on Debian for EFI ARM64 systems.
[images.efi-debian-arm64]
layer = "efi-debian"
architecture = "arm64"
target = "generic-grub-efi"
