# Use Raspberry Pi OS Bookworm as a basis for the custom image.
#
# Note that you can also declare your own base layer(s). For examples, see:
# https://github.com/silitics/rugpi/tree/main/repositories/core/layers
parent = "core/raspios-bookworm"

# Include recipes for the custom image.
recipes = [
    "core/raspberrypi",  # Prepares the Raspberry Pi base image for usage with Rugpi.
    "core/set-hostname",  # Sets a static hostname (see parameters below).
    "core/persist-root-home",  # Persists the home directory of the root user.
    "core/ssh",  # Configures SSH.
    "rugpi-extra/zsh",  # Installs ZSH.
    "rugpi-extra/nginx",  # Installs Nginx.
    "rugpi-extra/simple-sbom",  # Create a simple SBOM.
    "mender",  # Enable and configure the Mender client.
    "hello-world",  # Enable the `hello-world` recipe installing the static webpage.
]

[parameters."core/set-hostname"]
hostname = "rugpi-template-mender"

[parameters."core/apt-cleanup"]
autoremove = true

[parameters."core/ssh"]
root_authorized_keys = """
PLACE YOUR OWN PUBLIC SSH KEY HERE!
"""

[parameters."core/rugpi-ctrl"]
rugpi_admin = true  # Enable Rugpi Admin.

[parameters."rugpi-extra/simple-sbom"]
sbom_file = "build/customized.sbom.txt"
