name: Bake Images

on:
  workflow_dispatch:
  push:

env:
  NAME: "Mender Template"

jobs:  
  bake-image:
    name: Bake Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { image: rpi-raspios }
          - { image: rpi-raspios-pi4 }
          - { image: rpi-debian }
          - { image: efi-debian-amd64 }
          - { image: efi-debian-arm64 }
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install QEMU
        run: docker run --privileged --rm tonistiigi/binfmt --install arm64
      
      - name: Prepare and Configure
        env:
          SECRET_ENV: ${{ secrets.ENV || '' }}
        run: |
          mkdir build
          if [ -n "${SECRET_ENV}" ]; then
            echo "${SECRET_ENV}" > .env
          fi
      
      - name: Bake Image
        run: ./run-bakery bake image ${{ matrix.job.image }}

      - name: Build Mender Artifact
        run: |
          wget https://downloads.mender.io/mender-artifact/3.11.0/linux/mender-artifact
          chmod +x ./mender-artifact
          VERSION=$(date +'%Y%m%d.%H%M')
          ./mender-artifact write module-image \
              -n "${NAME} ${VERSION}" \
              -t raspberrypi4 \
              -T rugpi-image \
              -f build/images/${{ matrix.job.image }}.img \
              -o build/${VERSION}.mender \
              --software-name "${NAME}" \
              --software-version "${VERSION}"

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.job.image }}
      #     path: build/*