name: Bake Images

on:
  workflow_dispatch:
  push:

env:
  NAME: "Mender Template"

jobs:  
  bake-image:
    name: Bake Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install QEMU
        run: docker run --privileged --rm tonistiigi/binfmt --install arm64
      
      - name: Prepare and Configure
        env:
          SECRET_ENV: ${{secrets.ENV || ''}}
        run: |
          mkdir build
          if [ -n "${SECRET_ENV}" ]; then
            echo "${SECRET_ENV}" > .env
          fi
      
      - name: Bake Image (Pi4)
        run: ./run-bakery bake image pi4 build/pi4.img
      
      - name: Bake Image (Tryboot)
        run: ./run-bakery bake image tryboot build/tryboot.img

      - name: Build Mender Artifact
        run: |
          wget https://downloads.mender.io/mender-artifact/3.11.0/linux/mender-artifact
          chmod +x ./mender-artifact
          VERSION=$(date +'%Y%m%d.%H%M')
          ./mender-artifact write module-image \
              -n "${NAME} ${VERSION}" \
              -t raspberrypi4 \
              -T rugpi-image \
              -f build/tryboot.img \
              -o build/${VERSION}.mender \
              --software-name "${NAME}" \
              --software-version "${VERSION}"

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifacts
      #     path: build/*